daemon off;
master_process off;

load_module modules/libstream.so;
error_log error.log notice;

events { }

stream {
    server {
        listen 127.0.0.1:8000;
        stream_probe on;
        return "$stream_probe";
    }
}
