[package]
name = "nginx-src"
# Version format: <NGINX major>.<NGINX minor>.<crate patch>+<NGINX version>
version = "1.30.0+1.30.4"
# Crate sources are licensed under Apache-2.0, with exception of the
# NGINX submodule that is redistributed under BSD-2-Clause.
license = "Apache-2.0 AND BSD-2-Clause"
description = "Source of NGINX"
keywords = ["nginx", "module", "sys"]
exclude = [
    "/nginx/.git*",
    "/nginx/contrib",
    "/nginx/docs",
    "/nginx/misc",
    "!/nginx/docs/html",
    "!/nginx/docs/man",
]
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
duct = "1.1.1"
flate2 = "1.1.9"
shlex = "2.0.1"
tar = "0.4.46"
ureq = "3.2"

[dev-dependencies]
tempfile = { version = "3.27.0", default-features = false }

[lints]
workspace = true
