[package]
name = "nginx-src"
# Version format: <NGINX major>.<NGINX minor>.<crate patch>+<NGINX version>
version = "1.28.5+1.28.3"
# Crate sources are licensed under Apache-2.0, with exception of the
# NGINX submodule that is redistributed under BSD-2-Clause.
license = "Apache-2.0 AND BSD-2-Clause"
description = "Source of NGINX"
keywords = ["nginx", "module", "sys"]
exclude = [
    "/nginx/.git*",
    "/nginx/contrib",
    "/nginx/docs",
    "/nginx/misc",
    "!/nginx/docs/html",
    "!/nginx/docs/man",
]
edition = "2021"
homepage.workspace = true
repository.workspace = true
rust-version = "1.81.0"

[dependencies]
duct = "1.1.1"
flate2 = "1.1.9"
tar = "0.4.46"
ureq = "~3.2"

[lints]
workspace = true
